from pydantic import BaseModel, ConfigDict, Field

from src.domain.models.dataset import MinimalSource


class MinimalSearchResults(BaseModel):
    """
    Core search results for a single question.

    Attributes:
        question_id: Unique identifier for the question.
        question: The text of the question.
        retrieved_sources: List of sources identified by the retriever.
    """

    model_config = ConfigDict(extra="forbid")

    question_id: str
    question: str
    retrieved_sources: list[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """
    Search results along with a generated answer.

    Attributes:
        answer: The text of the answer generated by the system.
    """

    model_config = ConfigDict(extra="forbid")

    answer: str


class StudentSearchResults(BaseModel):
    """
    Collection of search results for evaluation.

    Attributes:
        k: The number of top results retrieved per question.
        search_results: List of search results for multiple questions.
    """

    model_config = ConfigDict(extra="forbid")

    k: int
    search_results: list[MinimalSearchResults] = Field(default_factory=list)


class StudentSearchResultsAndAnswer(BaseModel):
    """
    Collection of search results and answers for evaluation.

    Attributes:
        k: The number of top results retrieved per question.
        search_results: List of answers for multiple questions.
    """

    model_config = ConfigDict(extra="forbid")

    k: int
    search_results: list[MinimalAnswer] = Field(default_factory=list)
